[project]
name = "papercuts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyslang",
]

[tool.uv]
cache-dir = "./.uv_cache"

[tool.uv.sources]
pyslang = { git = "https://github.com/MikePopoloski/slang.git" }
